/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author hp 14
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    double v[],b[];
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmbCrear = new javax.swing.JButton();
        cmbManual = new javax.swing.JButton();
        cmbAutomatico = new javax.swing.JButton();
        cmbMostrar = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        cmbOperacion = new javax.swing.JComboBox<>();
        cmbManual2 = new javax.swing.JButton();
        cmbAutomatico2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Operaciones Con Vectores ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Longitud"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Longitud");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel3.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCrear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbCrear.setText("Crear");
        cmbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmbCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        cmbManual.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbManual.setText("Llenar Manual A");
        cmbManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbManualActionPerformed(evt);
            }
        });
        jPanel4.add(cmbManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cmbAutomatico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbAutomatico.setText("Llenar Automatico A");
        cmbAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutomaticoActionPerformed(evt);
            }
        });
        jPanel4.add(cmbAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmbMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbMostrar.setText("Mostrar");
        cmbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        cmbBorrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbBorrar.setText("Borrar");
        jPanel4.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        cmbOperacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Union", "Interseccion ", "Diferencia(A-B)", "Diferencia(B-A)" }));
        jPanel4.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 130, -1));

        cmbManual2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbManual2.setText("Llenar Manual B");
        cmbManual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbManual2ActionPerformed(evt);
            }
        });
        jPanel4.add(cmbManual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        cmbAutomatico2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbAutomatico2.setText("Llenar Automatico B");
        cmbAutomatico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutomatico2ActionPerformed(evt);
            }
        });
        jPanel4.add(cmbAutomatico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 320, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 240));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearActionPerformed
       int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite La Longitud","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
        }else if (Integer.parseInt(txtLongitud.getText().trim())==0) {
            JOptionPane.showMessageDialog(this, "La longitud no puede ser cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
             txtLongitud.selectAll();}
        else{
            longitud=Integer.parseInt(txtLongitud.getText().trim());
            v=new double[longitud];
            b=new double [longitud];
            JOptionPane.showMessageDialog(this, "Vectores Creados Exitosamente");
        }
    }//GEN-LAST:event_cmbCrearActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        char c=evt.getKeyChar();
         
        if(!Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void cmbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarActionPerformed
        for (int i = 0; i < v.length; i++) {
            if  (b[i]==0){
            JOptionPane.showMessageDialog(this, "Llene El Vector B", "Error", JOptionPane.ERROR_MESSAGE);
            break;
            }
            else if(v[i]==0){
            JOptionPane.showMessageDialog(this, "Llene El Vector A", "Error", JOptionPane.ERROR_MESSAGE);
            break;
            } 
        }
    }//GEN-LAST:event_cmbMostrarActionPerformed

    private void cmbManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbManualActionPerformed
       double n;
        for (int i=0;i<v.length;i++){
            n= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el Elemento En La Posicion "+i));
            v[i]=n;
        }
        JOptionPane.showMessageDialog(this, "Vector Creado Exitosamente");
    }//GEN-LAST:event_cmbManualActionPerformed

    private void cmbManual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbManual2ActionPerformed
        double n;
        for (int i=0;i<b.length;i++){
            n= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite el Elemento En La Posicion "+i));
            b[i]=n;
        }
        JOptionPane.showMessageDialog(this, "Vector Creado Exitosamente");
    }//GEN-LAST:event_cmbManual2ActionPerformed

    private void cmbAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutomaticoActionPerformed
       double n;
        for (int i = 0; i < v.length; i++) {
         n= (int) (Math.random()*50+1);
            v[i]=n;}
        for (int i = 0; i < v.length; i++) {
                    txtResultado.append(v[i]+" \n ");
                }
        JOptionPane.showMessageDialog(this, "Vector Creado Exitosamente");
    }//GEN-LAST:event_cmbAutomaticoActionPerformed

    private void cmbAutomatico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutomatico2ActionPerformed
        double n;
        for (int i = 0; i < b.length; i++) {
         n= (int) (Math.random()*50+1);
            b[i]=n;}
        for (int i = 0; i < b.length; i++) {
                    txtResultado.append(b[i]+" \n ");
                }
        JOptionPane.showMessageDialog(this, "Vector Creado Exitosamente");
    }//GEN-LAST:event_cmbAutomatico2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAutomatico;
    private javax.swing.JButton cmbAutomatico2;
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCrear;
    private javax.swing.JButton cmbManual;
    private javax.swing.JButton cmbManual2;
    private javax.swing.JButton cmbMostrar;
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
